# Generated by Django 3.2 on 2022-06-30 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_has_sizes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review', fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('name', models.CharField(
                        max_length=80)), ('body', models.TextField()), ('created_on', models.DateTimeField(
                            auto_now_add=True)), ('product', models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product')), ], ), ]
